[package]
name = "gbrustemu"
version = "0.1.0"
authors = ["douglas"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Cargo.toml
[dependencies]
minifb = "0.12"
